### ISSUE TITLE
Wrong reference for Pfahl E., Rappaport S., Podsiadlowski P., 2002

### ISSUE THREAD

**Issue by avigna** [FloorBroekgaarden/templateForTableBPSsettings#1]
Hi Floor!

currently using your handy table to describe a COMPAS simulation (thanks!). I noticed than Pfahl E., Rappaport S., Podsiadlowski P., 2002 is the wrong reference. 

Currently, it is: https://ui.adsabs.harvard.edu/abs/2002ApJ...571L..37P/abstract
Should be: https://ui.adsabs.harvard.edu/abs/2002ApJ...573..283P/abstract

I just updated it in the Overleaf. Let me know if you agree, and if so, maybe consider deleting the other reference from the bibtex file. Cheers, Alejandro

**Comment by FloorBroekgaarden** [comment]
Yes! Thanks for finding this! Ive deleted the wrong citation. Thanks so much!
